### PR TITLE
Add Reinfections data and graphs

### PR DESCRIPTION
**Pull request by RosalynLP**
Added

- Reinfections table to data tab
- Reinfections subtab on summary tab, with graphs for daily reinfections: count and cumulative
- New graph in reinfections tab - percent reinfections stacked barchart

Fixed issue with last LFT week being cut off

### CODE REVIEW

**Review by rubenv95 — CHANGES_REQUESTED** [review]
The tooltips aren't quite right, have NAs in them. 
I think it would be good to add the bar chart as well from the publication if possible but not essential for this week if there isn't time.

**Comment by rubenv95** [comment]
Two "Reinfections" appear in the data table drop-down, the second one being completely empty. Otherwise looks good to me

**Review by rubenv95 — APPROVED** [review]
Once you've removed the empty reinfections data table, happy for you to merge. 
Thanks for the additions, looks good!

**Comment by RosalynLP** [comment]
image

**Comment by rubenv95** [comment]
Looks great! Thanks

**Pull request merged**
