### PR TITLE
Standardise tables

### PR DESCRIPTION
**Pull request by RosalynLP**
Addresses #54 
The idea is to change the format of the csv files and update dashboard data transfer scripts accordingly such that the tables in the dashboard look better. Specifically

- [x] Fix bug where SIMD1 not displayed for positive PCR cases by deprivation
- [x] Change % formatting in tables to 1dp
- [x] Remove [] around ages for cases by age group
- [x] Make sure * appears for suppressed values rather than NA

### CODE REVIEW

**Comment by RosalynLP** [comment]
@rubenv95 would be good to merge this if we can

**Comment by rubenv95** [comment]
Oh sorry I thought this was a WIP still! I will look this afternoon

**Comment by RosalynLP** [comment]
Thanks! :)

**Review by rubenv95 — APPROVED** [review]
All looks sensible, thanks. Sorry for ignoring for a month, I had convinced myself it was waiting for more work to be done and no idea why.

**Comment by RosalynLP** [comment]
No problem! I forgot it existed as well until yesterday 🌵

**Pull request merged**
