### PR TITLE
Update tables to have nicer formatting

### PR DESCRIPTION
**Pull request by RosalynLP**
- Reverse order by date
- Highlight important rows/columns
- Use PHS colours
- Create functions for tables to avoid duplication of code

**Tables**
- [x] Data tab
- [x] Contact tracing data
- [x] Travel outside Scotland
- [x] Setting
- [x] HCW data
- [x] Care homes data
- [x] Quarantine data
- [x] LFD testing
- [x] LFD demographics
- [x] Targeted community testing data dropdown

### CODE REVIEW

**Review by rubenv95 — CHANGES_REQUESTED** [review]
I've checked the output. Here are some comments. Happy for some of these to be ignored (I'm aware some were outside the remit of this update) and we can look at down the line. 
Overall styles look great and reversing the order of dates all seems fine to me. Reordering of columns all makes sense. 

- Positive PCR cases by deprivation is missing SIMD 1
- Distribution of confirmed COVID-19 PCR cases by age group only goes up until 22-1-9. Is that correct? I would have thought we have more up to date data. Also age column has format "[0-17]" not "0-17"
- Proportion of weekly cases admitted to hospital by age group - % is 1dp, but mostly 2dp elsewhere. I'd personally say 1dp across the board (as with rates for example), but either way best to be consistent. 
- I wonder if Unknown category should be at the bottom rather than top? Eg NHS24 contacts by age and sex, positive PCR by age and sex. This could be a future issue however. 
- NHS 24 community outcomes - $Community Hub Outcome has "." between each outcome. Could these be replaced with spaces? 
- Community hubs and assessment centres by age - age group = "all" not "Total", so not consistent. 
- Scottish Ambulance Service by age and sex - "All" not "Total"
- Setting tab data table - "week ending" should be "Week Ending"
- Contact Tracing Data table - as above
- LFDs SIMD table - could add "(most/least deprived)" after 1/5. 
- Targeted community testing - data - There's a random "p" after the date for recent week?

**Comment by RosalynLP** [comment]
@rubenv95 thanks for the review! Here are my comments on the above:

1. Well spotted, this is an issue with the csv file so something must have gone wrong in the data transfer this week. I will track this down but it's not to do with this PR
2. Interesting, again this is because of what's in the csv. However the chart has two more weeks than this so we definitely have this elsewhere. Needs investigating.
3. This one is because the percentage formatting was done explicitly by you in the dashboard data transfer and so I didn't apply an additional formatting level. We can change the dashboard data transfer file to make it 1dp perhaps
4. Unknown category is a good one, but it's not really easy to do with regards to sorting. I agree this is a good future issue.
5. Replace . with spaces - will do that before merging (I've been putting this one off XD)
6. the all vs Total thing is again a csv issue. This needs standardised which would require changing dashboard data transfer scripts and the csvs themselves. Again, think this works best as a separate PR so as to not confuse things.
7. week ending for setting - will fix here
8. week ending for CT - will fi here
9. LFDs SIMD - think this is better changed in csvs, will do this in a separate PR
10. p means provisional so this is fine

**Comment by RosalynLP** [comment]
#53 and #54 are additional issues I made to address the bits I won't do in this PR.

**Comment by RosalynLP** [comment]
@rubenv95 I have committed the changes which I think are best done in this PR and created additional issues for the others. Lmk if you're happy to merge.

**Review by rubenv95 — APPROVED** [review]
Happy for these changes to be merged. Thank you.

**Pull request merged**
